### ISSUE TITLE
Slow Startup on Digital Ocean

### ISSUE THREAD

**Issue by csev** [Apereo-Learning-Analytics-Initiative/OpenLRW#22]
I installed OpenLRW and it took over 20 minutes to start up on Digital Ocean on a 2CPU/4GB Ubuntu server.  Turns out there is an "entropy problem" - here are my notes for the fix:

```
apt-get install haveged
update-rc.d haveged defaults
apt-get install rng-tools
cat /dev/random | rngtest -c 1000
```

- http://www.issihosts.com/haveged/
- https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged
- https://www.digitalocean.com/community/questions/fresh-tomcat-takes-loong-time-to-start-up
- https://stackoverflow.com/questions/27612209/spring-boot-application-wont-boot-at-startup-inside-docker

**Comment by leveque** [comment]
Is there more to do to close this issue?
