### ISSUE TITLE
Consider renaming packages from unicon to org.apereo

### ISSUE THREAD

**Issue by arwhyte** [Apereo-Learning-Analytics-Initiative/OpenLRW#25]
Apereo matters.  :)

**Comment by lsloan** [comment]
I'm available to make this change if @gryglbrt et al agree that this should be done.

**Comment by leveque** [comment]
@gryglbrt and all, is there a reason not to do this?

**Comment by gryglbrt** [comment]
No, I support the change

**Comment by leveque** [comment]
@lsloan, can you still make it?

**Comment by xchopin** [comment]
Done https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW/commit/0df9cdb2439faf9e795666c88bc07e2073abe256.
