### ISSUE TITLE
where is  OpenLRW client code?

### ISSUE THREAD

**Issue by chenzhikaida** [Apereo-Learning-Analytics-Initiative/OpenLRW#27]
i can't find OpenLRW Client in this repository.how can i find it ? thank you!

**Comment by gryglbrt** [comment]
Here are some examples of Java clients for OpenLRW [https://github.com/Apereo-Learning-Analytics-Initiative/OpenDashboard/blob/master/src/main/java/od/providers/matthews/MatthewsClient.java](url) and [https://github.com/Apereo-Learning-Analytics-Initiative/OpenDashboard/blob/master/src/main/java/od/providers/events/MatthewsEventProvider.java](url)
