### ISSUE TITLE
Java 9 Support

### ISSUE THREAD

**Issue by gryglbrt** [Apereo-Learning-Analytics-Initiative/OpenLRW#31]
OpenLRW fails to start when using Java 9.

**Comment by xchopin** [comment]
Java 9 is supported since Spring 2.0+ ([source](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes))

**Comment by xchopin** [comment]
Java SE 9 has reached end of support. Users of Java SE 9 should switch to Java SE 11.

This request is now closed.
