### ISSUE TITLE
xAPI to Caliper conversion: verb URIs

### ISSUE THREAD

**Issue by xchopin** [Apereo-Learning-Analytics-Initiative/OpenLRW#44]
Hi,

I'm currently adding xAPI events through Logstash scripts and we are facing an issue. 

In the xAPI JSON structure, there is a field `id` for the `verb` object such as : 
```javascript
"verb": {
         "id": "https://w3id.org/xapi/adl/verbs/logged-in",
          "display": {
            "en-US": "Logged in",
          }
}
```

At first, I googled websites that have an xAPI dictionary (I found w3id.org which is pretty nice) however I noticed the verb id isn't converted to Caliper; indeed this URI hasn't been added in [`DefaultXapiToCaliperConversionService.java`](https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW/blob/master/src/main/java/unicon/matthews/xapi/service/DefaultXapiToCaliperConversionService.java)

**My question is why are there so many different websites for verbs ? (tincanapi.com, brindlewaye.com, activitystrea.ms, etc...)**

Each time we have to check the java file to know which hostname has been picked for this verb.

Can I fix/pull request this and use the same hostname for all the verbs, or something like this ?

Thanks

**Comment by bseclier** [comment]
Hello @gryglbrt, do you have any advice about verbs we need to use? I'm currently developing scripts for adding different xAPI actions and I don't know what to use.
Thanks for your help.

**Comment by gryglbrt** [comment]
The issue is there are many vocabularies for xAPI and different event producers use different vocabularies and therefore different lists of verbs. Although much of the focus of OpenLRW has recently been on Caliper, we've tried to update the list of xapi verbs to match these two sources: https://github.com/adlnet-archive/xAPIVerbs/blob/master/verbs.js and https://registry.tincanapi.com/#home/verbs I would recommend that you start with those. Hope that helps - Gary

**Comment by xchopin** [comment]
Thanks for the answer, so I might update the java class to make it fit with the resources.

**Comment by bseclier** [comment]
Perfect, sure it will help :)
Thank you !

**Comment by bseclier** [comment]
Hello Gary,
We have a problem, I can see in Matthews code that we need to use specific verbs in order for them to be converted to caliper (DefaultXapiToCaliperConversionService.java). There is a lot of "old" verbs like brindlewaye.com or activitystrea.m, do you have any idea for changing it ?
Thanks,

**Comment by xchopin** [comment]
That was the point of my Github issue; so who maintains this part?

**Comment by gryglbrt** [comment]
At this point most OpenLRW users are focused on Caliper, I am comfortable with you making any changes that you need to DefaultXapiToCaliperConversionService in terms of adding new verb mappings however don't change any of the existing mappings until we cut a new release

**Comment by xchopin** [comment]
We'll see about Caliper format.

For sure we aren't gonna change the previous mapping; we don't want to ruin scripts of other users :)
