### ISSUE TITLE
xAPI to Caliper conversion

### ISSUE THREAD

**Issue by samjaved** [Apereo-Learning-Analytics-Initiative/OpenLRW#52]
Hello,

I am currently looking for an LRS to run locally to save xAPI statements.I have seen in this LRW every xAPI statement received is converted to Caliper format and then saved to LRS.Can we save the statements in xAPI format directly instead of converting them to Caliper format and then saving?

**Comment by xchopin** [comment]
Already answered in emails; you can close the ticket @gryglbrt .
