### ISSUE TITLE
Post data 

### ISSUE THREAD

**Issue by pexpert9** [Apereo-Learning-Analytics-Initiative/OpenLRW#54]
Hi ,

I have Question related POST request ? 
Can we send data through Authorization with username and password.
Because large data transfer can required to update API Key many times.
Token Reset regularly .
1. Can we fixed API key value (Not change automatically)
2. Code for POST data through Username and Password instead of API key.
Thanks

**Comment by xchopin** [comment]
You don't need a JWT for xAPI and Caliper routes otherwise you have to refresh the token. If I remember well, JWT lifetime is 3 hours.
