### ISSUE TITLE
Multiple JSON Object send through Post 

### ISSUE THREAD

**Issue by pexpert9** [Apereo-Learning-Analytics-Initiative/OpenLRW#55]
How to send Multiple Object through Rest POST method.
Actually I have create an array but It propagate Message..
=============================================================
{
    "status": "BAD_REQUEST",
    "messages": [
        "Can not deserialize instance of unicon.matthews.caliper.Envelope$Builder out of START_ARRAY token"
    ],
    "path": "/api/caliper/",
===============================================================

**Comment by xchopin** [comment]
Caliper only supports one event at a time, you cannot send multiple objects for now.
