### ISSUE TITLE
Caliper - Can not construct instance of unicon.matthews.caliper.Agent$Builder

### ISSUE THREAD

**Issue by jrissler** [Apereo-Learning-Analytics-Initiative/OpenLRW#57]
I'm getting this error:

`{"status":"BAD_REQUEST","messages":["Can not construct instance of unicon.matthews.caliper.Agent$Builder: no String-argument constructor/factory method to deserialize from String value (''https://platform.example.org'')"],"path":"/api/caliper","timestamp":"2018-08-10T19:02:53.382"}`

Sending the following as POST w valid credentials:
https://gist.github.com/jrissler/d308d5a78049151dc5ffa296f9a7d5fa - not sure whats up?

**Comment by gryglbrt** [comment]
@jrissler Looks like the issue here is that the LRW is expecting the edApp value to be an object of type Agent and not a simple string. Definitely something to be fixed - hopefully within the next week or two.

**Comment by jrissler** [comment]
@gryglbrt ok thanks that helps, I can update my event to support what's expected for now, and then update back once a fix is in place - appreciate the help!
