### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by zandrews22** [Apereo-Learning-Analytics-Initiative/OpenLRW#7]
Hello,
I am working with OpenLRW and am trying to set it up on my host machine
where I have my MongoBD. I have confirmed that it does connect with my
mongoDB. I see that in the github updates you mentioned a UI however when I
go to localhost:9966 i get a whitlelabel error saying there is no explicit
mapping. is this correct or is there something wrong with my configuration?
or is this just the endpoint to send data to with no ui created?

**Comment by gryglbrt** [comment]
Hi,

You can check to see if OpenLRW is running by hitting the /info endpoint from your browser.

**Comment by reynlds-illinois** [comment]
What other endpoints are available? To what endpoint do I send events from my source(s)?

**Comment by gryglbrt** [comment]
@reynlds-illinois What kinds of events are you trying to send to the LRW - xAPI or Caliper?

**Comment by reynlds-illinois** [comment]
Caliper

**Comment by gryglbrt** [comment]
Here is some information on the Caliper endpoints in OpenLRW - [https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW#e-caliper-routes](https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW#e-caliper-routes)

**Comment by pexpert9** [comment]
Please provide Mongodb URI format used in run.sh file : 








#!/bin/sh
cd `dirname $0`
APP_HOME="$PWD"
PID_FILE=$APP_HOME/run/openlrw.pid
JAR_PATH=$APP_HOME/lib/openlrw.jar

cd $APP_HOME

case "$1" in
"start")
  if [ -f $PID_FILE ]; then
    exit 1
  fi
  java \
    -Dlogging.path=/opt/openlrw/logs/ \
    -Dspring.data.mongodb.uri= \
    -jar $JAR_PATH &
  echo $! > $PID_FILE
  ;;
"stop")
  if [ ! -f $PID_FILE ]; then
    exit 1
  fi
  kill `cat $PID_FILE`
  rm -f $PID_FILE
  ;;
*)
  echo "Usage: $0 start|stop"
  ;;
esac
exit 0

**Comment by pexpert9** [comment]
How to send Multiple Object through Rest POST method.
Actually I have create an array but It propagate Message..
{
"status": "BAD_REQUEST",
"messages": [
"Can not deserialize instance of unicon.matthews.caliper.Envelope$Builder out of START_ARRAY token"
],
"path": "/api/caliper/",
