### ISSUE TITLE
Converting UTC time sent in Caliper Event again as it local time sent

### ISSUE THREAD

**Issue by abg35** [Apereo-Learning-Analytics-Initiative/OpenLRW#71]
We sending caliper events to an openLRW setup on our server.  We are sending the sensor sendTime, and the event eventTime in UTC format, but the openLRW is again converting the time as if it were local time.  

Ex.  the event.eventTime field sent to openLRW is "2018-12-04T15:29:22Z"
but what gets stored in the mongo Event  for event.eventTime is ISODate("2018-12-04T20:29:22Z")

This is a big issue for us, because we are doing data analysis by local date, and this throws the data off.

I can't find in the code where this conversion is taking place.

**Comment by abg35** [comment]
Hi Xavier,


Thank you for replying to me.   I am sending the Caliper data using the caliper-php library provided on the imsglobal GitHub site, and it is definitely sending the timestamps in ISO8601 UTC format.


This Morning I sent a caliper event to our OpenLRW the with the timestamp : "eventTime":"2018-12-05T15:21:51.000Z"


However, when I look at the event stored in the mongodb by the OpenLRW, the field contains: "eventTime" : ISODate("2018-12-05T20:21:51Z")


Any idea why this is happening?


Thanks,

Anna


________________________________

**Comment by xchopin** [comment]
Did you try to send the eventTime in UNIX timestamp (eg: 1544023311 for the one you gave)?

**Comment by abg35** [comment]
If I send a unix timestamp for event time, as in:


"eventTime":1544107666


I get a 400 bad request error:


{
"status": 400,
"reason": "Bad Request",
"method": "POST",
"path": "/key/caliper",
"parameters": {},
"messages": [
"Unexpected token (VALUE_NUMBER_INT), expected VALUE_STRING: Expected array or string."
]
}
________________________________

**Comment by xchopin** [comment]
You forgot to add quotes around your timestamp

**Comment by abg35** [comment]
So, I did another test sending the unix timestamp as a string, and got the following response:


{
"status": 400,
"reason": "Bad Request",
"method": "POST",
"path": "/key/caliper",
"parameters": {},
"messages": [
"Can not deserialize value of type java.time.LocalDateTime from String \"1544108012\": Text '1544108012' could not be parsed at index 0"
]
}

It looks like the event time is defined as LocalDateTime... and that seems be the problem... it seems to be ignoring that fact that I am sending as UTC, and interpreting as local time anyway.

The problem is that the caliper standard clearly specifies that the timestamp should be sent as UTC. This is in the eventTime spec :

eventTime       DateTime        An ISO 8601 date and time value expressed with millisecond precision that indicates when the Event<https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html#event> occurred. The value MUST be expressed using the format YYYY-MM-DDTHH:mm:ss.SSSZ set to UTC with no offset specified.






from here:

https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html#event


________________________________

**Comment by abg35** [comment]
In your python script,


datetime.datetime.fromtimestamp(YOUR_TIMESTAMP).isoformat()

You are not actually converting your timestamp to UTC as required by the spec.

I believe you can use

datetime.utcfromtimestamp


________________________________

**Comment by xchopin** [comment]
Maybe, but it works very well with our timezone ahah

**Comment by gryglbrt** [comment]
Definitely an issue with using LocalDateTime incorrectly. We will see about replacing LocalDateTime with Instant (or something similar) in the next week or so. Stay tuned.

**Comment by abg35** [comment]
Thanks!

________________________________

**Comment by xchopin** [comment]
I am starting to fix the issue. The issue is located is in this repository: https://github.com/Apereo-Learning-Analytics-Initiative/lai-event

**Comment by xchopin** [comment]
@abg35 I converted event datetimes to Instant https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW/commit/2aa35e75769a83e32de9d600544e7d34e7c7c1f1

Is it working now ?

**Comment by abg35** [comment]
Thanks for fixing that.  Unfortunately, I don't currently have a development environment to test the changes.  We have a pilot running now which is collecting data for the semester, so I won't be able to test this until we get our new environment up and running, or the end of the semester.

________________________________

**Comment by xchopin** [comment]
I just tested from our web application, it works very well. Don't forget to change the value of the  `date.timezone` field in the `php.ini` file
