### ISSUE TITLE
org.apereo.openlrw.caliper.*

### ISSUE THREAD

**Issue by uvilop** [Apereo-Learning-Analytics-Initiative/OpenLRW#82]
some java file import classes from a org.apereo.openlrw.caliper package, but this is not in the src tree.
where can i find them ?

**Comment by jrchamp** [comment]
Are these the ones? https://github.com/Apereo-Learning-Analytics-Initiative/lai-event

**Comment by xchopin** [comment]
> some java file import classes from a org.apereo.openlrw.caliper package, but this is not in the src tree.
> where can i find them ?

https://www.facebook.com/yannOb241/videos/2704431782978930/UzpfSTEwMDAwMDY3NjA2MTE5MTozMTAxODIyNDg5ODYzMTAy/ :)

**Comment by xchopin** [comment]
@uvilop you can find this information into the documentation on this [page]( https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW/blob/master/docs/faq.md#i-dont-find-all-the-entities-eg-oneroster-models-where-are-these-classes)
